[package]
cairo-version = "2.16.0"
name = "chimera_forge"
version = "0.1.0"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[dependencies]
starknet = "2.16.0"
dojo = "1.8.6"

[tool.scarb]
allow-prebuilt-plugins = ["dojo_cairo_macros"]

[[target.starknet-contract]]
build-external-contracts = ["dojo::world::world_contract::world"]

[dev-dependencies]
cairo_test = "2.16.0"
dojo_cairo_test = "1.8.6"
